version: "3"
services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/srv/app/public
      ##Now when we change a file in the public folder, all you need to do is refresh the page instead of editing the URL
